simulation:
  length: 168
  analyze_start: 72
  analyze_end: 120
  train_number: 26
  train_batch_size: 200
yard:
  yard_type: parallel
  track_number: 5
  receiving_track_numbers: 10
  railcar_length: 60
  d_f: 15
  d_x: 15
terminal:
  cranes_per_track: 4
  hostler_number: 360
  hostler_diesel_percentage: 1
gates:
  in_gate_numbers: 500
  out_gate_numbers: 500
layout:
  file_path: input/layout.xlsx
  mode: adaptive
  M: 5
  N: 5
  n_t: 2
  n_p: 2
  n_r: 20
emissions:
  load_consumption:
    crane_loaded:
      Diesel: 2.6
      Hybrid: 9.04
    crane_idle:
      Diesel: 1.2
      Hybrid: 0.4
  trip_consumption:
    hostler_empty:
      Diesel: 1.11
      Electric: 2.78
    hostler_loaded:
      Diesel: 1.94
      Electric: 3.66
    truck_empty:
      Diesel: 1.11
      Electric: 2.68
    truck_loaded:
      Diesel: 1.94
      Electric: 3.66
  side_pick_consumption:
    side:
      Diesel: 2.88
      Electric: 0.21
