simulation:
  simul_weeks: 4       # total of weeks
  length: 700          # total hours of weeks + cool-down time; 3-weeks: 24*21=504 or 4-weeks: 24*28=672
  analyze_start: 168    # beg of week 2; 24*7=168
  analyze_end: 336      # end of week 2; 24*14=336
  random_seed: 42
timetable:
  vessel:
    enabled: true         # false to disable mode generation (i.e. intermodal terminal)
    weekly_num: 1          # one-vessel arrives per week
    batch_size: 1100
    destination_split:
      train: 0.6
      truck: 0.4
  train:
    enabled: true
    batch_size: 100
  truck:
    enabled: true
    batch_size: 1         # single-stacked
terminal:                 # terminal resources
  cranes_per_berth: 10
  cranes_per_track: 4
  hostler_number: 1000
  hostler_diesel_percentage: 1
yard:
  yard_type: parallel
  berth_number: 3
  receiving_track_numbers: 10
  railcar_length: 60
gates:
  in_gate_numbers: 500
  out_gate_numbers: 500
layout:
  file_path: input/layout.xlsx
  mode: adaptive
  M: 5
  N: 5
  n_t: 2
  n_p: 2
  n_r: 20
emissions:
  load_consumption:
    crane_loaded:
      Diesel: 2.6
      Hybrid: 9.04
    crane_idle:
      Diesel: 1.2
      Hybrid: 0.4
  trip_consumption:
    hostler_empty:
      Diesel: 1.11
      Electric: 2.78
    hostler_loaded:
      Diesel: 1.94
      Electric: 3.66
    truck_empty:
      Diesel: 1.11
      Electric: 2.68
    truck_loaded:
      Diesel: 1.94
      Electric: 3.66
  side_pick_consumption:
    side:
      Diesel: 2.88
      Electric: 0.21