simulation:
  length: 48               # total simulation time (hours)
  train_number: 10          # number of trains in the simulation
  train_batch_size: 100     # full_cars = oc_number = truck_number

yard:
  yard_type: parallel
  track_number: 2             # tracks to process containers
  receiving_track_numbers: 10 # tracks to hold decoupled railcars
  railcar_length: 60          # railcar length (joint + railcar; ft)
  d_f: 15                     # crossing offset (ft)
  d_x: 15                     # track spacing (ft)

terminal:
  cranes_per_track: 2         # assume evenly distributed cranes on tracks
  hostler_number: 18          # all hostlers are shared between tracks
  hostler_diesel_percentage: 1 # percentage of diesel hostlers (decimal between 0 to 1)

gates:
  in_gate_numbers: 3        # truck entrance gate
  out_gate_numbers: 3       # truck exit gate

layout:
  file_path: "input/layout.xlsx"   # yard geometry file
  mode: adaptive                   # 'fixed' or 'adaptive'

  # Note: if mode == 'fixed' (i.e. simulation for a specific yard), use default parameters below
  M: 5         # rows of parking blocks
  N: 5         # cols of parking blocks
  n_t: 2       # train aisles per group
  n_p: 2       # parking aisles per group
  n_r: 20      # pairs of parking slots